### ISSUE TITLE
demo_plane has no thrust

### ISSUE THREAD

**Issue by mclau152** [addmix/godot_aerodynamic_physics#24]
demo_plane has no thrust it should have a way to thrust by default

**Comment by addmix** [comment]
Which version of the plugin are you using?

**Comment by addmix** [comment]
This commit fixes it.
https://github.com/addmix/godot_aerodynamic_physics/commit/c6840872a1bd59b8c56abd041072b96b86ed7dbf

**Comment by mclau152** [comment]
I am still having a lot of trouble with demo_scene.tscn and demo_plane and thrust, I am seeing mass acceleration rate being printed out and  would assume throttle up SHIFT key or throttle down CTRL key would do something but I truly believe it is not doing anything, can you please check to see how demo_scene.tscn and demo_plane.tscn are working?

**Comment by mclau152** [comment]
@icon("../icons/JetThrusterComponent.svg")
          extends Marker3D
          class_name AeroThrusterComponent
          
          const AeroNodeUtils = preload("../utils/node_utils.gd")
          
          @onready var rigid_body : RigidBody3D = AeroNodeUtils.get_first_parent_of_type(self, RigidBody3D)
          ##Enables simulation of the JetThrusterComponent.
          @export var enabled : bool = true
          @export_group("Control")
          ##If enabled, throttle is automatically read from the ancestor AeroBody3D.
          @export var get_throttle_from_aero_body : bool = true
          ##Throttle value used to simulate the JetThrusterComponent
          @export var throttle : float = 1.0
          
          @export_group("Simulation Parameters")
          ##Area (in meters squared) of the JetThrusterComponent's intake.
          @export var intake_area : float = 0.5
          ##Area (in meters squared) of the JetThrusterComponent's exhaust. (Unused)
          #@export var exit_area : float = 1.0
          ##Maxmimum air velocity the intake fan can create in static thrust, at max throttle.
          @export var intake_fan_max_velocity : float = 100.0
          ##Velocity of exhaust gasses at max throttle.
          @export var exhaust_velocity : float = 1000
          ##Maximum amount of fuel (in kilograms) the engine can burn per second.
          @export var max_fuel_flow : float = 0.1 #flow rate in kilograms per second
          ##Ratio of fuel volume before, and after combustion. (Unused)
          #@export var fuel_expansion_ratio : float = 10.0
          var throttle_step : float = 0.1  # How much throttle changes per input
          var min_throttle : float = 0.0
          var max_throttle : float = 1.0
          
          func _physics_process(delta : float) -> void:
	          if not enabled:
		          return
	          
	          # Handle throttle input if not getting it from aero body
	          if not get_throttle_from_aero_body:
		          # Increase throttle
		          if Input.is_action_pressed("throttle_up"):
			          throttle = clamp(throttle + throttle_step * delta, min_throttle, max_throttle)
		          
		          # Decrease throttle
		          if Input.is_action_pressed("throttle_down"):
			          throttle = clamp(throttle - throttle_step * delta, min_throttle, max_throttle)
	          
	          # Calculate force
	          var mass_acceleration_rate : float = calculate_mass_flow_acceleration()
	          var force_magnitude : float = mass_acceleration_rate * delta
	          print(mass_acceleration_rate)
	          print(throttle)
	          if rigid_body:
		          rigid_body.apply_force(-global_transform.basis.z * force_magnitude, rigid_body.global_transform.basis * position)
	          
	          if rigid_body is AeroBody3D and get_throttle_from_aero_body:
		          throttle = rigid_body.throttle_command

**Comment by mclau152** [comment]
I believe this fixes the throttle input issues

**Comment by addmix** [comment]
The demo scene doesn't have any throttle control, as I hadn't found any appropriate built-in InputMap actions to fill that role. (`ui_*` events). Because you are modifying the demo plane, your issue is probably due to the throttle input being set to `1.0` here:
![image](https://github.com/user-attachments/assets/178e29ed-2bb7-4798-8ce7-d8100442c558)
I suppose it isn't a perfect way to demonstrate how to properly use the AeroControlComponent, and is a very small detail, which is easy to overlook. I will change the demo plane to use the `ui_page_up` and `ui_page_down` actions for throttle control instead. This change is in commit: 193255c7da71bd91b9b573cb9db87dd03d97bdeb

However, hard-coded input logic inside the `AeroThrusterComponent` script won't be needed, as binding inputs in the AeroControlComponent provides the expected functionality, assuming that the throttle input hasn't been set to `1.0`.

As a sidenote, the `input` value on the control config is used as a pass-through value. It isn't modified by the control config, and it exists as a way to script custom control schemes, without losing the convenience of the AeroControlComponent.
![image](https://github.com/user-attachments/assets/a9f6be7e-4d47-4229-9442-325b5a4134fb)
